const ProductionOrder = require("../models/ProductionOrder");
const BOM = require("../models/BOM");
const Inventory = require("../models/Inventory");
const PurchaseRequisition = require("../models/PurchaseRequisition");

const getNextOrderNumber = async () => {
  const count = await ProductionOrder.countDocuments();
  return `PRD-${String(count + 1).padStart(4, "0")}`;
};

const getNextPRNumber = async () => {
  const count = await PurchaseRequisition.countDocuments();
  return `PR-${String(count + 1).padStart(4, "0")}`;
};

/**
 * THE MRP CHECK — this is the core PP logic.
 *
 * Given a BOM and the quantity of finished product to make:
 *  1. For each component in the BOM, multiply quantityRequired x order quantity
 *     to get the total amount of that material needed.
 *  2. Compare against that material's availableStock (currentStock - reservedStock).
 *  3. If every component has enough -> reserve the stock, mark materialsAvailable = true.
 *  4. If ANY component is short -> record the shortfall, auto-generate a single
 *     Purchase Requisition covering every short item, mark materialsAvailable = false.
 */
const runMRPCheck = async (bom, orderQuantity, requestedByUserId) => {
  const shortfalls = [];
  const sufficientItems = []; // { inv, required } - only committed if EVERYTHING is sufficient

  for (const component of bom.components) {
    const required = component.quantityRequired * orderQuantity;
    const inv = await Inventory.findOne({ material: component.material });
    const available = inv ? inv.currentStock - inv.reservedStock : 0;

    if (available < required) {
      shortfalls.push({
        material: component.material,
        required,
        available,
        shortBy: required - available,
      });
    } else {
      sufficientItems.push({ inv, required });
    }
  }

  const materialsAvailable = shortfalls.length === 0;

  if (materialsAvailable) {
    // Only reserve stock once we know ALL components have enough - avoids partially
    // reserving materials for an order that can't actually be fulfilled.
    for (const { inv, required } of sufficientItems) {
      inv.reservedStock += required;
      await inv.save();
    }
    return { materialsAvailable: true, shortfalls: [], generatedPR: null };
  }

  // Short on at least one material -> auto-generate a Purchase Requisition for the gaps
  const pr = await PurchaseRequisition.create({
    prNumber: await getNextPRNumber(),
    department: "Production (auto-generated by MRP)",
    items: shortfalls.map((s) => ({ material: s.material, quantity: s.shortBy })),
    priority: "high",
    requestedBy: requestedByUserId,
    source: "mrp",
    status: "pending",
  });

  return { materialsAvailable: false, shortfalls, generatedPR: pr._id };
};

// POST /api/production-orders
// Body: { bom, quantity, startDate, endDate, priority, workCenter }
const createProductionOrder = async (req, res) => {
  try {
    const { bom: bomId, quantity, startDate, endDate, priority, workCenter } = req.body;

    if (!quantity || quantity <= 0) {
      return res.status(400).json({ message: "quantity must be a positive number" });
    }

    const bom = await BOM.findById(bomId);
    if (!bom) return res.status(400).json({ message: "BOM not found" });
    if (bom.status !== "active") {
      return res.status(400).json({ message: "Cannot use an archived BOM for production" });
    }

    const mrpResult = await runMRPCheck(bom, quantity, req.user._id);

    const order = await ProductionOrder.create({
      orderNumber: await getNextOrderNumber(),
      bom: bom._id,
      productName: bom.productName,
      quantity,
      startDate,
      endDate,
      priority,
      workCenter,
      status: mrpResult.materialsAvailable ? "released" : "planned",
      mrpResult,
      createdBy: req.user._id,
    });

    res.status(201).json({
      order,
      mrpSummary: mrpResult.materialsAvailable
        ? "All materials available. Stock reserved and order released to production."
        : "Material shortfall detected. A Purchase Requisition was auto-generated for the missing quantities. Order is on hold until stock arrives.",
    });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
};

// GET /api/production-orders  (supports ?status=)
const getProductionOrders = async (req, res) => {
  try {
    const { status } = req.query;
    const filter = {};
    if (status) filter.status = status;

    const orders = await ProductionOrder.find(filter)
      .populate("bom", "bomId productName")
      .populate("mrpResult.shortfalls.material", "materialId name unit")
      .populate("mrpResult.generatedPR", "prNumber status")
      .populate("createdBy", "name email")
      .sort({ createdAt: -1 });
    res.json(orders);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// GET /api/production-orders/:id
const getProductionOrderById = async (req, res) => {
  try {
    const order = await ProductionOrder.findById(req.params.id)
      .populate({ path: "bom", populate: { path: "components.material", select: "materialId name unit" } })
      .populate("mrpResult.shortfalls.material", "materialId name unit")
      .populate("mrpResult.generatedPR", "prNumber status")
      .populate("createdBy", "name email");
    if (!order) return res.status(404).json({ message: "Production Order not found" });
    res.json(order);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// PUT /api/production-orders/:id/retry-mrp
// Re-runs the MRP check - use this after the shortfall's PR has been fulfilled (goods received)
const retryMRP = async (req, res) => {
  try {
    const order = await ProductionOrder.findById(req.params.id).populate("bom");
    if (!order) return res.status(404).json({ message: "Production Order not found" });
    if (order.status !== "planned") {
      return res.status(400).json({ message: "Only orders still in 'planned' status can be retried" });
    }

    const mrpResult = await runMRPCheck(order.bom, order.quantity, req.user._id);
    order.mrpResult = mrpResult;
    order.status = mrpResult.materialsAvailable ? "released" : "planned";
    await order.save();

    res.json({
      order,
      mrpSummary: mrpResult.materialsAvailable
        ? "Materials now available. Stock reserved and order released."
        : "Still short on materials.",
    });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
};

module.exports = { createProductionOrder, getProductionOrders, getProductionOrderById, retryMRP };