const mongoose = require("mongoose");

const prItemSchema = new mongoose.Schema(
  {
    material: { type: mongoose.Schema.Types.ObjectId, ref: "Material", required: true },
    quantity: { type: Number, required: true, min: 1 },
  },
  { _id: false }
);

const purchaseRequisitionSchema = new mongoose.Schema(
  {
    prNumber: { type: String, required: true, unique: true }, // e.g. PR-0001
    department: { type: String, default: "" },
    items: { type: [prItemSchema], required: true },
    priority: { type: String, enum: ["low", "medium", "high", "urgent"], default: "medium" },
    requiredDate: { type: Date },
    requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    // Distinguishes manually-raised PRs from ones auto-generated by MRP shortfall
    source: { type: String, enum: ["manual", "mrp"], default: "manual" },
    linkedProductionOrder: { type: mongoose.Schema.Types.ObjectId, ref: "ProductionOrder", default: null },
    status: { type: String, enum: ["pending", "approved", "rejected", "converted"], default: "pending" },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: true }
);

module.exports = mongoose.model("PurchaseRequisition", purchaseRequisitionSchema);
